language: node_js
node_js:
  - "10"

script:
  - yarn build

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  local_dir: content/.vuepress/dist
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  repo: sails-guide/sails-guide.github.io
  keep-history: true
  target-branch: master
  on:
    branch: master
